export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';

export const PRODUCT_UPDATE_INPUT = 'PRODUCT_UPDATE_INPUT';
export const PRODUCT_RESET_INPUT = 'PRODUCT_RESET_INPUT';
export const PRODUCT_IMPORT = 'PRODUCT_IMPORT';
export const PRODUCT_INITIALIZE = 'PRODUCT_INITIALIZE';


export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_FAILED = 'ADD_REVIEW_FAILED';

export const REVIEW_UPDATE_INPUT = 'REVIEW_UPDATE_INPUT';
export const REVIEW_RESET_INPUT = 'REVIEW_RESET_INPUT';


export const ADD_ERRORS = 'ADD_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_PAGE_INDEX = 'SET_PAGE_INDEX';

export const EXECUTE_SEARCH = 'EXECUTE_SEARCH';
export const SEARCH_UPDATE_INPUT = 'SEARCH_UPDATE_INPUT';
export const SEARCH_RESET_INPUT = 'SEARCH_RESET_INPUT';


export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_IMPORT = 'USER_IMPORT';
export const USER_UPDATE_INPUT = 'USER_UPDATE_INPUT';
export const USER_RESET_INPUT = 'USER_RESET_INPUT';